import Foundation
import Testing
import DoomKitProcess

struct UnitTests {
    @Test func publicUnitsPreserveDefinitions() {
        #expect(UnitPopulation.people.symbol == "n")
        #expect(UnitPopulation.people.converter.baseUnitValue(fromValue: 1) == 1.0)
        #expect(UnitPopulation.thousand.symbol == "k")
        #expect(UnitPopulation.thousand.converter.baseUnitValue(fromValue: 1) == 1000.0)
        #expect(UnitPopulation.million.symbol == "M")
        #expect(UnitPopulation.million.converter.baseUnitValue(fromValue: 1) == 1000000.0)
        #expect(UnitPopulation.baseUnit() == UnitPopulation.people)
        #expect(UnitTurbidity.fnu.symbol == "FNU")
        #expect(UnitTurbidity.fnu.converter.baseUnitValue(fromValue: 1) == 1.0)
        #expect(UnitTurbidity.baseUnit() == UnitTurbidity.fnu)
        #expect(UnitIncidence.casesPer100k.symbol == "\u{2081}\u{2080}\u{2080}\u{2096}")
        #expect(UnitIncidence.casesPer100k.converter.baseUnitValue(fromValue: 1) == 1.0)
        #expect(UnitIncidence.casesPer1000k.symbol == "\u{2081}\u{2080}\u{2080}\u{2080}\u{2096}")
        #expect(UnitIncidence.casesPer1000k.converter.baseUnitValue(fromValue: 1) == 0.1)
        #expect(UnitIncidence.baseUnit() == UnitIncidence.casesPer100k)
        #expect(UnitRadiation.sieverts.symbol == "Sv/h")
        #expect(UnitRadiation.sieverts.converter.baseUnitValue(fromValue: 1) == 1.0)
        #expect(UnitRadiation.millisieverts.symbol == "mSv/h")
        #expect(UnitRadiation.millisieverts.converter.baseUnitValue(fromValue: 1) == 0.001)
        #expect(UnitRadiation.microsieverts.symbol == "µSv/h")
        #expect(UnitRadiation.microsieverts.converter.baseUnitValue(fromValue: 1) == 0.000001)
        #expect(UnitRadiation.grays.symbol == "Gy/h")
        #expect(UnitRadiation.grays.converter.baseUnitValue(fromValue: 1) == 1.0)
        #expect(UnitRadiation.baseUnit() == UnitRadiation.sieverts)
        #expect(UnitElectricalConductivity.millisiemensPerCentimeter.symbol == "mS/cm")
        #expect(UnitElectricalConductivity.millisiemensPerCentimeter.converter.baseUnitValue(fromValue: 1) == 0.1)
        #expect(UnitElectricalConductivity.siemensPerMeter.symbol == "S/m")
        #expect(UnitElectricalConductivity.siemensPerMeter.converter.baseUnitValue(fromValue: 1) == 1.0)
        #expect(UnitElectricalConductivity.baseUnit() == UnitElectricalConductivity.millisiemensPerCentimeter)
        #expect(UnitPercentage.percent.symbol == "%")
        #expect(UnitPercentage.percent.converter.baseUnitValue(fromValue: 1) == 1.0)
        #expect(UnitPercentage.permille.symbol == "‰")
        #expect(UnitPercentage.permille.converter.baseUnitValue(fromValue: 1) == 0.1)
        #expect(UnitPercentage.baseUnit() == UnitPercentage.percent)
        #expect(UnitAcidity.pH.symbol == "pH")
        #expect(UnitAcidity.pH.converter.baseUnitValue(fromValue: 1) == 1.0)
        #expect(UnitAcidity.baseUnit() == UnitAcidity.pH)
        #expect(UnitConcentrationMass.microgramsPerCubicMeter.symbol == "µg/m³")
        #expect(UnitConcentrationMass.microgramsPerCubicMeter.converter.baseUnitValue(fromValue: 1) == 0.000001)
        #expect(UnitConcentrationMass.milligramsPerCubicMeter.symbol == "mg/m³")
        #expect(UnitConcentrationMass.milligramsPerCubicMeter.converter.baseUnitValue(fromValue: 1) == 0.001)
        #expect(UnitConcentrationMass.nanogramsPerCubicMeter.symbol == "ng/m³")
        #expect(UnitConcentrationMass.nanogramsPerCubicMeter.converter.baseUnitValue(fromValue: 1) == 0.000000001)
        #expect(Measurement(value: 1, unit: UnitRadiation.sieverts).converted(to: .microsieverts).value == 1_000_000)
        #expect(Measurement(value: 1, unit: UnitPopulation.million).converted(to: .thousand).value == 1000)
        #expect(Measurement(value: 10, unit: UnitPercentage.permille).converted(to: .percent).value == 1)
        let value = ProcessValue(value: Measurement(value: 1, unit: UnitAcidity.pH), customData: ["source": "fixture"], quality: .good, timestamp: .distantPast)
        #expect(value.value.unit == .pH)
        #expect(value.quality == .good)
        #expect(value.customData?["source"] as? String == "fixture")
        #expect(value.timestamp == .distantPast)
    }
}
